/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import com.mongodb.client.MongoCursor;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author emili
 */
public class Interfaz_Alumno extends javax.swing.JFrame {

    
    private String dnialumno;
    /**
     * Creates new form Interfaz_Alumno
     */
    public Interfaz_Alumno(String dni) {
        this.dnialumno = dni;
        this.setLocationRelativeTo(null);
        initComponents();
        llenarlicencias();
        JC_LicenciaMatricular.setSelectedIndex(-1);
        for(int i = 0; i < licencias.size(); i++){
            String licencia = (String)licencias.get(i).get("tipo");
            JC_LicenciaMatricular.removeItem(licencia);
        }    
    }

    private void llenarlicencias(){
        Document doc = new Document();
        doc.append("dni", dnialumno);
        licencias = (ArrayList<Document>)(((MongoCursor<Document>)conn.estudiantes.find(doc).iterator()).next().get("licencias"));
        
        doc = new Document();
        doc.append("alumno_dni", dnialumno);
        doc.append("pagado", false);
        pagos.clear();
        conn.pagos.find(doc).into(pagos);
        DefaultTableModel model = (DefaultTableModel)TB_Pagos.getModel();
        for(Document p : pagos){
            Object[] row = {
                false, p.get("descripcion"), p.get("costo")
            };
            model.addRow(row);
        }
        TB_Pagos.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Costos = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        TB_Pagos = new javax.swing.JTable();
        jSeparator27 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        JD_CP_BG20 = new javax.swing.JLabel();
        JD_CP_BG21 = new javax.swing.JLabel();
        JD_Matriculas = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        JC_ProfesorMatricular = new javax.swing.JComboBox<>();
        JC_LicenciaMatricular = new javax.swing.JComboBox<>();
        B_Matricular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JD_Licencias = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Licencias = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BT_Matricular = new javax.swing.JButton();
        BT_Licencias = new javax.swing.JButton();
        BT_Pagos = new javax.swing.JButton();

        JD_Costos.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_Costos.setResizable(false);
        JD_Costos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TB_Pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "✓", "Descripcion", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TB_Pagos);
        if (TB_Pagos.getColumnModel().getColumnCount() > 0) {
            TB_Pagos.getColumnModel().getColumn(0).setResizable(false);
            TB_Pagos.getColumnModel().getColumn(0).setPreferredWidth(5);
            TB_Pagos.getColumnModel().getColumn(1).setResizable(false);
            TB_Pagos.getColumnModel().getColumn(2).setResizable(false);
        }

        JD_Costos.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 460, 340));

        jSeparator27.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator27.setForeground(new java.awt.Color(101, 255, 138));
        JD_Costos.getContentPane().add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Pagar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JD_Costos.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 140, 40));

        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(101, 255, 138));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Pagos Pendientes");
        JD_Costos.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        JD_CP_BG20.setBackground(new java.awt.Color(51, 42, 36));
        JD_CP_BG20.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG20.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG20.setOpaque(true);
        JD_CP_BG20.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Costos.getContentPane().add(JD_CP_BG20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG21.setBackground(new java.awt.Color(50, 175, 0));
        JD_CP_BG21.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG21.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG21.setOpaque(true);
        JD_CP_BG21.setPreferredSize(new java.awt.Dimension(600, 570));
        JD_Costos.getContentPane().add(JD_CP_BG21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JD_Matriculas.setMinimumSize(new java.awt.Dimension(550, 350));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JC_ProfesorMatricular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Motociclista", "Liviana", "Pesada" }));
        JC_ProfesorMatricular.setSelectedIndex(-1);
        jPanel2.add(JC_ProfesorMatricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 240, -1));

        JC_LicenciaMatricular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Motociclista", "Liviana", "Pesada" }));
        JC_LicenciaMatricular.setSelectedIndex(-1);
        JC_LicenciaMatricular.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JC_LicenciaMatricularItemStateChanged(evt);
            }
        });
        jPanel2.add(JC_LicenciaMatricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 240, -1));

        B_Matricular.setText("Matricular");
        B_Matricular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B_MatricularMousePressed(evt);
            }
        });
        jPanel2.add(B_Matricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 90, 40));

        jLabel2.setText("Profesor");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel1.setText("Licencia");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        JD_Matriculas.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Mis Licencias");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 100, 40));

        jButton2.setText("OK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 80, -1));

        TB_Licencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Fecha", "Calificacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TB_Licencias);
        if (TB_Licencias.getColumnModel().getColumnCount() > 0) {
            TB_Licencias.getColumnModel().getColumn(0).setResizable(false);
            TB_Licencias.getColumnModel().getColumn(1).setResizable(false);
            TB_Licencias.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 410, 200));

        javax.swing.GroupLayout JD_LicenciasLayout = new javax.swing.GroupLayout(JD_Licencias.getContentPane());
        JD_Licencias.getContentPane().setLayout(JD_LicenciasLayout);
        JD_LicenciasLayout.setHorizontalGroup(
            JD_LicenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        JD_LicenciasLayout.setVerticalGroup(
            JD_LicenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 350));
        setPreferredSize(new java.awt.Dimension(800, 390));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 310));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BT_Matricular.setBackground(new java.awt.Color(255, 92, 0));
        BT_Matricular.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        BT_Matricular.setForeground(new java.awt.Color(51, 51, 51));
        BT_Matricular.setText("Matricular");
        BT_Matricular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Matricular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_MatricularMousePressed(evt);
            }
        });
        BT_Matricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_MatricularActionPerformed(evt);
            }
        });
        jPanel1.add(BT_Matricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 250, 70));

        BT_Licencias.setBackground(new java.awt.Color(153, 51, 0));
        BT_Licencias.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        BT_Licencias.setForeground(new java.awt.Color(255, 255, 255));
        BT_Licencias.setText("Mis Licencias ");
        BT_Licencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Licencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_LicenciasMousePressed(evt);
            }
        });
        jPanel1.add(BT_Licencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 250, 70));

        BT_Pagos.setBackground(new java.awt.Color(50, 175, 0));
        BT_Pagos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        BT_Pagos.setForeground(new java.awt.Color(51, 51, 51));
        BT_Pagos.setText("Pagos Pendientes");
        BT_Pagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_PagosMousePressed(evt);
            }
        });
        jPanel1.add(BT_Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 250, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_MatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_MatricularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_MatricularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BT_PagosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_PagosMousePressed
        Abrir_JDialog(JD_Costos);
    }//GEN-LAST:event_BT_PagosMousePressed

    private void BT_MatricularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_MatricularMousePressed
        Abrir_JDialog(JD_Matriculas);
    }//GEN-LAST:event_BT_MatricularMousePressed

    private void JC_LicenciaMatricularItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JC_LicenciaMatricularItemStateChanged
        if(JC_LicenciaMatricular.getSelectedIndex() >= 0){
            String tipo = (String)JC_LicenciaMatricular.getSelectedItem();
            MongoCursor<Document> cursor = conn.profesores.find(new Document("ensenia",tipo)).iterator();
            JC_ProfesorMatricular.removeAllItems();
            while(cursor.hasNext()){
                Document dc = cursor.next();
                JC_ProfesorMatricular.addItem( (String)dc.get("dni") + " | " + (String)dc.get("nombre"));
            }
        }
    }//GEN-LAST:event_JC_LicenciaMatricularItemStateChanged

    private void B_MatricularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_MatricularMousePressed
        if(JC_LicenciaMatricular.getSelectedIndex() >= 0){
            String tipo = (String)JC_LicenciaMatricular.getSelectedItem();
            String dniprofesor = (String)JC_ProfesorMatricular.getSelectedItem();
            dniprofesor = dniprofesor.substring(0, dniprofesor.indexOf("|")-1);
            Document dc = new Document();
            dc.append("alumno_dni", dnialumno);
            dc.append("profesor_dni", dniprofesor);
            dc.append("tipo", tipo);
            conn.practicas.insertOne(dc);
            if(licencias.size() > 0){
                Document dc2 = new Document();
                dc2.append("alumno_dni", dnialumno);
                dc2.append("descripcion", "Examen Teorico");
                dc2.append("costo", 50);
                dc2.append("pagado", false);
                conn.pagos.insertOne(dc2);	
            }
            Document dc3 = new Document();
            dc3.append("alumno_dni", dnialumno);
            dc3.append("descripcion", "Matricula para Licencia " + tipo);
            dc3.append("costo", 100);
            dc3.append("pagado", false);
            conn.pagos.insertOne(dc3);
            JC_LicenciaMatricular.removeItem(tipo);
            JC_ProfesorMatricular.removeAllItems();
            JC_LicenciaMatricular.setSelectedIndex(-1);
            JD_Matriculas.setVisible(false);
            JOptionPane.showMessageDialog(this, "Se matriculo exitosamente");
        }
    }//GEN-LAST:event_B_MatricularMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        DefaultTableModel model = (DefaultTableModel)TB_Pagos.getModel();
        for(int i = 0; i < model.getRowCount(); i++){
            if((boolean)model.getValueAt(i, 0)){
                Document dc = pagos.get(i);
                conn.pagos.updateOne(dc, new Document("$set", new Document("pagado", true)));
            }
        }
        while(model.getRowCount() > 0)
            model.removeRow(0);
        llenarlicencias();
        JOptionPane.showMessageDialog(JD_Costos, "Se hizo el pago exitosamente");
    }//GEN-LAST:event_jButton1MousePressed

    private void BT_LicenciasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_LicenciasMousePressed
        DefaultTableModel model = (DefaultTableModel)TB_Licencias.getModel();
        while(model.getRowCount() > 0)
            model.removeRow(0);
        for(Document l : licencias){
            Object[] row = {
                l.get("tipo"),l.get("fecha"),l.get("calificacion")
            };
            model.addRow(row);
        }
        TB_Licencias.setModel(model);
        Abrir_JDialog(JD_Licencias);
    }//GEN-LAST:event_BT_LicenciasMousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        JD_Licencias.setVisible(false);
    }//GEN-LAST:event_jButton2MousePressed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Licencias;
    private javax.swing.JButton BT_Matricular;
    private javax.swing.JButton BT_Pagos;
    private javax.swing.JButton B_Matricular;
    private javax.swing.JComboBox<String> JC_LicenciaMatricular;
    private javax.swing.JComboBox<String> JC_ProfesorMatricular;
    private javax.swing.JLabel JD_CP_BG20;
    private javax.swing.JLabel JD_CP_BG21;
    private javax.swing.JDialog JD_Costos;
    private javax.swing.JDialog JD_Licencias;
    private javax.swing.JDialog JD_Matriculas;
    private javax.swing.JTable TB_Licencias;
    private javax.swing.JTable TB_Pagos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator27;
    // End of variables declaration//GEN-END:variables
    
    private void Abrir_JDialog(JDialog JD) {
        JD.setModal(true);
        JD.pack();
        JD.setLocationRelativeTo(null);//this Frame
        JD.setVisible(true);
    }
    
    private ArrayList<Document> licencias = new ArrayList<>();
    private ArrayList<Document> pagos = new ArrayList<>();
}
