/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import com.mongodb.client.MongoCursor;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.bson.Document;

/**
 *
 * @author emili
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Crear_Profesor = new javax.swing.JDialog();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        CP_BT_Crear = new javax.swing.JButton();
        CP_CB_LicenciaEnseniar = new javax.swing.JComboBox<>();
        CP_TF_Password = new javax.swing.JTextField();
        CP_TF_Nombre = new javax.swing.JTextField();
        CP_TF_Correo = new javax.swing.JTextField();
        CP_TF_DNI = new javax.swing.JTextField();
        JD_CP_BG = new javax.swing.JLabel();
        JD_CP_BG1 = new javax.swing.JLabel();
        JD_Modificar_Profesor = new javax.swing.JDialog();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        MP_BT_Modificar = new javax.swing.JButton();
        MP_CB_Profesor = new javax.swing.JComboBox<>();
        MP_CB_LicenciaEnseniar = new javax.swing.JComboBox<>();
        MP_TF_Password = new javax.swing.JTextField();
        MP_TF_Correo = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        JD_CP_BG2 = new javax.swing.JLabel();
        JD_CP_BG3 = new javax.swing.JLabel();
        JD_Eliminar_Profesor = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        EP_BT_Eliminar = new javax.swing.JButton();
        EP_CB_Profesor = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        JD_CP_BG4 = new javax.swing.JLabel();
        JD_CP_BG5 = new javax.swing.JLabel();
        JD_Crear_Alumno = new javax.swing.JDialog();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        CA_BT_Crear = new javax.swing.JButton();
        CA_TF_Password = new javax.swing.JTextField();
        CA_TF_Nombre = new javax.swing.JTextField();
        CA_TF_Correo = new javax.swing.JTextField();
        CA_TF_DNI = new javax.swing.JTextField();
        JD_CP_BG8 = new javax.swing.JLabel();
        JD_CP_BG9 = new javax.swing.JLabel();
        JD_Modificar_Alumno = new javax.swing.JDialog();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        MA_BT_Modificar = new javax.swing.JButton();
        MA_CB_Alumno = new javax.swing.JComboBox<>();
        MA_TF_Password = new javax.swing.JTextField();
        MA_TF_Correo = new javax.swing.JTextField();
        JD_CP_BG10 = new javax.swing.JLabel();
        JD_CP_BG11 = new javax.swing.JLabel();
        JD_Eliminar_Alumno = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        EA_BT_Eliminar = new javax.swing.JButton();
        EA_CB_Alumno = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        JD_CP_BG6 = new javax.swing.JLabel();
        JD_CP_BG7 = new javax.swing.JLabel();
        JD_Crear_Vehiculo = new javax.swing.JDialog();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        CV_CB_Profesor = new javax.swing.JComboBox<>();
        CV_TF_Modelo = new javax.swing.JTextField();
        CV_TF_Matricula = new javax.swing.JTextField();
        CV_TF_Marca = new javax.swing.JTextField();
        CV_SP_Tarifa = new javax.swing.JSpinner();
        CV_BT_Crear = new javax.swing.JButton();
        JD_CP_BG14 = new javax.swing.JLabel();
        JD_CP_BG15 = new javax.swing.JLabel();
        JD_Modificar_Vehiculo = new javax.swing.JDialog();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        MV_BT_Modificar = new javax.swing.JButton();
        MV_CB_Vehiculo = new javax.swing.JComboBox<>();
        MV_CB_Estado = new javax.swing.JComboBox<>();
        MV_TF_Modelo = new javax.swing.JTextField();
        MV_TF_Matricula = new javax.swing.JTextField();
        MV_TF_Marca = new javax.swing.JTextField();
        MV_SP_Tarifa = new javax.swing.JSpinner();
        JD_CP_BG16 = new javax.swing.JLabel();
        JD_CP_BG17 = new javax.swing.JLabel();
        JD_Eliminar_Vehiculo = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        EV_BT_Eliminar = new javax.swing.JButton();
        EV_CB_Vehiculo = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        JD_CP_BG12 = new javax.swing.JLabel();
        JD_CP_BG13 = new javax.swing.JLabel();
        JD_Listar_Profesor = new javax.swing.JDialog();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        LP_ScrollPane = new javax.swing.JScrollPane();
        LP_TB_Profesores = new javax.swing.JTable();
        JD_CP_BG18 = new javax.swing.JLabel();
        JD_CP_BG19 = new javax.swing.JLabel();
        JD_Listar_Alumno = new javax.swing.JDialog();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        LP_ScrollPane1 = new javax.swing.JScrollPane();
        LP_TB_Alumnos = new javax.swing.JTable();
        JD_CP_BG20 = new javax.swing.JLabel();
        JD_CP_BG21 = new javax.swing.JLabel();
        JD_Listar_Vehiculo = new javax.swing.JDialog();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        LP_ScrollPane2 = new javax.swing.JScrollPane();
        LP_TB_Vehiculos = new javax.swing.JTable();
        JD_CP_BG22 = new javax.swing.JLabel();
        JD_CP_BG23 = new javax.swing.JLabel();
        JD_RegistroPagos = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Pagos = new javax.swing.JTable();
        JD_RegistroCalificaciones = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TB_Calificaciones = new javax.swing.JTable();
        CRUD_BG = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        BT_Listar_Profesor = new javax.swing.JButton();
        BT_Listar_Alumno = new javax.swing.JButton();
        BT_Listar_Vehiculo = new javax.swing.JButton();
        BT_Crear_Profesor = new javax.swing.JButton();
        BT_Crear_Alumno = new javax.swing.JButton();
        BT_Crear_Vehiculo = new javax.swing.JButton();
        BT_Modificar_Profesor = new javax.swing.JButton();
        BT_Modificar_Alumno = new javax.swing.JButton();
        BT_Modificar_Vehiculo = new javax.swing.JButton();
        BT_Eliminar_Profesor = new javax.swing.JButton();
        BT_Eliminar_Alumno = new javax.swing.JButton();
        BT_Eliminar_Vehiculo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        BT_RegistrosCalificaciones = new javax.swing.JButton();
        BT_RegistrosPagos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        JD_Crear_Profesor.setBounds(new java.awt.Rectangle(0, 0, 600, 520));
        JD_Crear_Profesor.setMinimumSize(new java.awt.Dimension(600, 520));
        JD_Crear_Profesor.setResizable(false);
        JD_Crear_Profesor.setSize(new java.awt.Dimension(600, 520));
        JD_Crear_Profesor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator17.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator17.setForeground(new java.awt.Color(177, 147, 130));
        JD_Crear_Profesor.getContentPane().add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(214, 188, 164));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Crear Profesor");
        JD_Crear_Profesor.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        jLabel69.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel69.setText("Nombre");
        JD_Crear_Profesor.getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 20));

        jLabel71.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel71.setText("Licencia a Enseñar");
        JD_Crear_Profesor.getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 20));

        jLabel72.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel72.setText("Correo");
        JD_Crear_Profesor.getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, 20));

        jLabel73.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel73.setText("Contraseña");
        JD_Crear_Profesor.getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, 20));

        jLabel81.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel81.setText("DNI");
        JD_Crear_Profesor.getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 20));

        CP_BT_Crear.setBackground(new java.awt.Color(29, 91, 49));
        CP_BT_Crear.setText("Crear");
        CP_BT_Crear.setBorderPainted(false);
        CP_BT_Crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CP_BT_Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CP_BT_CrearMousePressed(evt);
            }
        });
        JD_Crear_Profesor.getContentPane().add(CP_BT_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 110, -1));

        CP_CB_LicenciaEnseniar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Motociclista", "Liviana", "Pesada" }));
        CP_CB_LicenciaEnseniar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CP_CB_LicenciaEnseniarActionPerformed(evt);
            }
        });
        JD_Crear_Profesor.getContentPane().add(CP_CB_LicenciaEnseniar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 290, -1));
        JD_Crear_Profesor.getContentPane().add(CP_TF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 290, -1));
        JD_Crear_Profesor.getContentPane().add(CP_TF_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 290, -1));
        JD_Crear_Profesor.getContentPane().add(CP_TF_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 290, -1));
        JD_Crear_Profesor.getContentPane().add(CP_TF_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 290, -1));

        JD_CP_BG.setBackground(new java.awt.Color(51, 42, 36));
        JD_CP_BG.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG.setOpaque(true);
        JD_CP_BG.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Crear_Profesor.getContentPane().add(JD_CP_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG1.setBackground(new java.awt.Color(79, 66, 57));
        JD_CP_BG1.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG1.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG1.setOpaque(true);
        JD_CP_BG1.setPreferredSize(new java.awt.Dimension(600, 520));
        JD_Crear_Profesor.getContentPane().add(JD_CP_BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        JD_Modificar_Profesor.setMinimumSize(new java.awt.Dimension(600, 490));
        JD_Modificar_Profesor.setResizable(false);
        JD_Modificar_Profesor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator18.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator18.setForeground(new java.awt.Color(177, 147, 130));
        JD_Modificar_Profesor.getContentPane().add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(214, 188, 164));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Modificar Profesor");
        JD_Modificar_Profesor.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        jLabel76.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel76.setText("Profesor");
        JD_Modificar_Profesor.getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 20));

        jLabel77.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel77.setText("Correo");
        JD_Modificar_Profesor.getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, 20));

        jLabel78.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel78.setText("Contraseña");
        JD_Modificar_Profesor.getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, 20));

        MP_BT_Modificar.setBackground(new java.awt.Color(40, 77, 119));
        MP_BT_Modificar.setText("Modificar");
        MP_BT_Modificar.setBorderPainted(false);
        MP_BT_Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MP_BT_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MP_BT_ModificarMousePressed(evt);
            }
        });
        JD_Modificar_Profesor.getContentPane().add(MP_BT_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 110, -1));

        MP_CB_Profesor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MP_CB_ProfesorItemStateChanged(evt);
            }
        });
        MP_CB_Profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MP_CB_ProfesorActionPerformed(evt);
            }
        });
        JD_Modificar_Profesor.getContentPane().add(MP_CB_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 290, -1));

        MP_CB_LicenciaEnseniar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Motociclista", "Liviana", "Pesada" }));
        MP_CB_LicenciaEnseniar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MP_CB_LicenciaEnseniarActionPerformed(evt);
            }
        });
        JD_Modificar_Profesor.getContentPane().add(MP_CB_LicenciaEnseniar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 290, -1));
        JD_Modificar_Profesor.getContentPane().add(MP_TF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 290, -1));
        JD_Modificar_Profesor.getContentPane().add(MP_TF_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 290, -1));

        jLabel79.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel79.setText("Enseñar");
        JD_Modificar_Profesor.getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 20));

        JD_CP_BG2.setBackground(new java.awt.Color(51, 42, 36));
        JD_CP_BG2.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG2.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG2.setOpaque(true);
        JD_CP_BG2.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Modificar_Profesor.getContentPane().add(JD_CP_BG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG3.setBackground(new java.awt.Color(79, 66, 57));
        JD_CP_BG3.setMaximumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG3.setMinimumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG3.setOpaque(true);
        JD_CP_BG3.setPreferredSize(new java.awt.Dimension(600, 550));
        JD_Modificar_Profesor.getContentPane().add(JD_CP_BG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JD_Eliminar_Profesor.setResizable(false);
        JD_Eliminar_Profesor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel16.setText("Profesor");
        JD_Eliminar_Profesor.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 20));

        EP_BT_Eliminar.setBackground(new java.awt.Color(99, 32, 39));
        EP_BT_Eliminar.setText("Eliminar");
        EP_BT_Eliminar.setBorderPainted(false);
        EP_BT_Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EP_BT_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EP_BT_EliminarMousePressed(evt);
            }
        });
        JD_Eliminar_Profesor.getContentPane().add(EP_BT_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        JD_Eliminar_Profesor.getContentPane().add(EP_CB_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 240, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(214, 188, 164));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Eliminar Profesor");
        JD_Eliminar_Profesor.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        jSeparator19.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator19.setForeground(new java.awt.Color(177, 147, 130));
        JD_Eliminar_Profesor.getContentPane().add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        JD_CP_BG4.setBackground(new java.awt.Color(51, 42, 36));
        JD_CP_BG4.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG4.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG4.setOpaque(true);
        JD_CP_BG4.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Eliminar_Profesor.getContentPane().add(JD_CP_BG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG5.setBackground(new java.awt.Color(79, 66, 57));
        JD_CP_BG5.setMaximumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG5.setMinimumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG5.setOpaque(true);
        JD_CP_BG5.setPreferredSize(new java.awt.Dimension(600, 490));
        JD_Eliminar_Profesor.getContentPane().add(JD_CP_BG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        JD_Crear_Alumno.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_Crear_Alumno.setResizable(false);
        JD_Crear_Alumno.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator21.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator21.setForeground(new java.awt.Color(249, 98, 0));
        JD_Crear_Alumno.getContentPane().add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 161, 101));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Crear Alumno");
        JD_Crear_Alumno.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        jLabel91.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel91.setText("Nombre");
        JD_Crear_Alumno.getContentPane().add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 20));

        jLabel93.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel93.setText("Correo");
        JD_Crear_Alumno.getContentPane().add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, 20));

        jLabel94.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel94.setText("Contraseña");
        JD_Crear_Alumno.getContentPane().add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, 20));

        jLabel95.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel95.setText("DNI");
        JD_Crear_Alumno.getContentPane().add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, 20));

        CA_BT_Crear.setBackground(new java.awt.Color(29, 91, 49));
        CA_BT_Crear.setText("Crear");
        CA_BT_Crear.setBorderPainted(false);
        CA_BT_Crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CA_BT_Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CA_BT_CrearMousePressed(evt);
            }
        });
        JD_Crear_Alumno.getContentPane().add(CA_BT_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 110, -1));
        JD_Crear_Alumno.getContentPane().add(CA_TF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 290, -1));
        JD_Crear_Alumno.getContentPane().add(CA_TF_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 290, -1));
        JD_Crear_Alumno.getContentPane().add(CA_TF_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 290, -1));
        JD_Crear_Alumno.getContentPane().add(CA_TF_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, -1));

        JD_CP_BG8.setBackground(new java.awt.Color(51, 42, 36));
        JD_CP_BG8.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG8.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG8.setOpaque(true);
        JD_CP_BG8.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Crear_Alumno.getContentPane().add(JD_CP_BG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG9.setBackground(new java.awt.Color(175, 69, 0));
        JD_CP_BG9.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG9.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG9.setOpaque(true);
        JD_CP_BG9.setPreferredSize(new java.awt.Dimension(600, 490));
        JD_Crear_Alumno.getContentPane().add(JD_CP_BG9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JD_Modificar_Alumno.setMinimumSize(new java.awt.Dimension(600, 540));
        JD_Modificar_Alumno.setResizable(false);
        JD_Modificar_Alumno.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator22.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator22.setForeground(new java.awt.Color(249, 98, 0));
        JD_Modificar_Alumno.getContentPane().add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 161, 101));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Modificar Alumno");
        JD_Modificar_Alumno.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        jLabel87.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel87.setText("Alumno");
        JD_Modificar_Alumno.getContentPane().add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 20));

        jLabel88.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel88.setText("Correo");
        JD_Modificar_Alumno.getContentPane().add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 20));

        jLabel89.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel89.setText("Contraseña");
        JD_Modificar_Alumno.getContentPane().add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, 20));

        MA_BT_Modificar.setBackground(new java.awt.Color(40, 77, 119));
        MA_BT_Modificar.setText("Modificar");
        MA_BT_Modificar.setBorderPainted(false);
        MA_BT_Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MA_BT_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MA_BT_ModificarMousePressed(evt);
            }
        });
        JD_Modificar_Alumno.getContentPane().add(MA_BT_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 110, -1));

        MA_CB_Alumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MA_CB_AlumnoItemStateChanged(evt);
            }
        });
        MA_CB_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MA_CB_AlumnoActionPerformed(evt);
            }
        });
        JD_Modificar_Alumno.getContentPane().add(MA_CB_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, -1));
        JD_Modificar_Alumno.getContentPane().add(MA_TF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 290, -1));
        JD_Modificar_Alumno.getContentPane().add(MA_TF_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 290, -1));

        JD_CP_BG10.setBackground(new java.awt.Color(51, 42, 36));
        JD_CP_BG10.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG10.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG10.setOpaque(true);
        JD_CP_BG10.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Modificar_Alumno.getContentPane().add(JD_CP_BG10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG11.setBackground(new java.awt.Color(175, 69, 0));
        JD_CP_BG11.setMaximumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG11.setMinimumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG11.setOpaque(true);
        JD_CP_BG11.setPreferredSize(new java.awt.Dimension(600, 540));
        JD_Modificar_Alumno.getContentPane().add(JD_CP_BG11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JD_Eliminar_Alumno.setResizable(false);
        JD_Eliminar_Alumno.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel17.setText("Alumno");
        JD_Eliminar_Alumno.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 20));

        EA_BT_Eliminar.setBackground(new java.awt.Color(99, 32, 39));
        EA_BT_Eliminar.setText("Eliminar");
        EA_BT_Eliminar.setBorderPainted(false);
        EA_BT_Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EA_BT_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EA_BT_EliminarMousePressed(evt);
            }
        });
        JD_Eliminar_Alumno.getContentPane().add(EA_BT_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        JD_Eliminar_Alumno.getContentPane().add(EA_CB_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 240, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 161, 101));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Eliminar Alumno");
        JD_Eliminar_Alumno.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        jSeparator20.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator20.setForeground(new java.awt.Color(249, 98, 0));
        JD_Eliminar_Alumno.getContentPane().add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        JD_CP_BG6.setBackground(new java.awt.Color(51, 42, 36));
        JD_CP_BG6.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG6.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG6.setOpaque(true);
        JD_CP_BG6.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Eliminar_Alumno.getContentPane().add(JD_CP_BG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG7.setBackground(new java.awt.Color(175, 69, 0));
        JD_CP_BG7.setMaximumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG7.setMinimumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG7.setOpaque(true);
        JD_CP_BG7.setPreferredSize(new java.awt.Dimension(600, 490));
        JD_Eliminar_Alumno.getContentPane().add(JD_CP_BG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        JD_Crear_Vehiculo.setMinimumSize(new java.awt.Dimension(600, 440));
        JD_Crear_Vehiculo.setResizable(false);
        JD_Crear_Vehiculo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator24.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator24.setForeground(new java.awt.Color(255, 0, 0));
        JD_Crear_Vehiculo.getContentPane().add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(232, 137, 137));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Crear Vehículo");
        JD_Crear_Vehiculo.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        jLabel107.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel107.setText("Modelo");
        JD_Crear_Vehiculo.getContentPane().add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 20));

        jLabel108.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel108.setText("Profesor");
        JD_Crear_Vehiculo.getContentPane().add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 20));

        jLabel109.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel109.setText("Matricula");
        JD_Crear_Vehiculo.getContentPane().add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 20));

        jLabel111.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel111.setText("Marca");
        JD_Crear_Vehiculo.getContentPane().add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, 20));

        jLabel110.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel110.setText("Tarifa");
        JD_Crear_Vehiculo.getContentPane().add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 20));

        CV_CB_Profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CV_CB_ProfesorActionPerformed(evt);
            }
        });
        JD_Crear_Vehiculo.getContentPane().add(CV_CB_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 290, -1));
        JD_Crear_Vehiculo.getContentPane().add(CV_TF_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 290, -1));
        JD_Crear_Vehiculo.getContentPane().add(CV_TF_Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 290, -1));
        JD_Crear_Vehiculo.getContentPane().add(CV_TF_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 290, -1));

        CV_SP_Tarifa.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));
        JD_Crear_Vehiculo.getContentPane().add(CV_SP_Tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 110, -1));

        CV_BT_Crear.setBackground(new java.awt.Color(29, 91, 49));
        CV_BT_Crear.setText("Crear");
        CV_BT_Crear.setBorderPainted(false);
        CV_BT_Crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CV_BT_Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CV_BT_CrearMousePressed(evt);
            }
        });
        CV_BT_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CV_BT_CrearActionPerformed(evt);
            }
        });
        JD_Crear_Vehiculo.getContentPane().add(CV_BT_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 110, -1));

        JD_CP_BG14.setBackground(new java.awt.Color(51, 0, 0));
        JD_CP_BG14.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG14.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG14.setOpaque(true);
        JD_CP_BG14.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Crear_Vehiculo.getContentPane().add(JD_CP_BG14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG15.setBackground(new java.awt.Color(132, 11, 11));
        JD_CP_BG15.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG15.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG15.setOpaque(true);
        JD_CP_BG15.setPreferredSize(new java.awt.Dimension(600, 440));
        JD_Crear_Vehiculo.getContentPane().add(JD_CP_BG15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        JD_Modificar_Vehiculo.setMinimumSize(new java.awt.Dimension(600, 540));
        JD_Modificar_Vehiculo.setResizable(false);
        JD_Modificar_Vehiculo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator25.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator25.setForeground(new java.awt.Color(255, 0, 0));
        JD_Modificar_Vehiculo.getContentPane().add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(232, 137, 137));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Modificar Vehículo");
        JD_Modificar_Vehiculo.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        jLabel101.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel101.setText("Modelo");
        JD_Modificar_Vehiculo.getContentPane().add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 20));

        jLabel102.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel102.setText("Tarifa");
        JD_Modificar_Vehiculo.getContentPane().add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, 20));

        jLabel103.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel103.setText("Vehículo");
        JD_Modificar_Vehiculo.getContentPane().add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 20));

        jLabel104.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel104.setText("Matricula");
        JD_Modificar_Vehiculo.getContentPane().add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 20));

        jLabel105.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel105.setText("Estado");
        JD_Modificar_Vehiculo.getContentPane().add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, 20));

        jLabel106.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel106.setText("Marca");
        JD_Modificar_Vehiculo.getContentPane().add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, 20));

        MV_BT_Modificar.setBackground(new java.awt.Color(40, 77, 119));
        MV_BT_Modificar.setText("Modificar");
        MV_BT_Modificar.setBorderPainted(false);
        MV_BT_Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MV_BT_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MV_BT_ModificarMousePressed(evt);
            }
        });
        JD_Modificar_Vehiculo.getContentPane().add(MV_BT_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 110, -1));

        MV_CB_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MV_CB_VehiculoActionPerformed(evt);
            }
        });
        JD_Modificar_Vehiculo.getContentPane().add(MV_CB_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, -1));

        JD_Modificar_Vehiculo.getContentPane().add(MV_CB_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 290, -1));
        JD_Modificar_Vehiculo.getContentPane().add(MV_TF_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 290, -1));
        JD_Modificar_Vehiculo.getContentPane().add(MV_TF_Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 290, -1));
        JD_Modificar_Vehiculo.getContentPane().add(MV_TF_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 290, -1));

        MV_SP_Tarifa.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));
        JD_Modificar_Vehiculo.getContentPane().add(MV_SP_Tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 110, -1));

        JD_CP_BG16.setBackground(new java.awt.Color(51, 0, 0));
        JD_CP_BG16.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG16.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG16.setOpaque(true);
        JD_CP_BG16.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Modificar_Vehiculo.getContentPane().add(JD_CP_BG16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG17.setBackground(new java.awt.Color(132, 11, 11));
        JD_CP_BG17.setMaximumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG17.setMinimumSize(new java.awt.Dimension(600, 470));
        JD_CP_BG17.setOpaque(true);
        JD_CP_BG17.setPreferredSize(new java.awt.Dimension(600, 470));
        JD_Modificar_Vehiculo.getContentPane().add(JD_CP_BG17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JD_Eliminar_Vehiculo.setResizable(false);
        JD_Eliminar_Vehiculo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel19.setText("Vehículo");
        JD_Eliminar_Vehiculo.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 20));

        EV_BT_Eliminar.setBackground(new java.awt.Color(99, 32, 39));
        EV_BT_Eliminar.setText("Eliminar");
        EV_BT_Eliminar.setBorderPainted(false);
        EV_BT_Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EV_BT_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EV_BT_EliminarMousePressed(evt);
            }
        });
        JD_Eliminar_Vehiculo.getContentPane().add(EV_BT_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        JD_Eliminar_Vehiculo.getContentPane().add(EV_CB_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 240, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(232, 137, 137));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Eliminar Vehículo");
        JD_Eliminar_Vehiculo.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        jSeparator23.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator23.setForeground(new java.awt.Color(255, 0, 0));
        JD_Eliminar_Vehiculo.getContentPane().add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        JD_CP_BG12.setBackground(new java.awt.Color(51, 0, 0));
        JD_CP_BG12.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG12.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG12.setOpaque(true);
        JD_CP_BG12.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Eliminar_Vehiculo.getContentPane().add(JD_CP_BG12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG13.setBackground(new java.awt.Color(132, 11, 11));
        JD_CP_BG13.setMaximumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG13.setMinimumSize(new java.awt.Dimension(600, 490));
        JD_CP_BG13.setOpaque(true);
        JD_CP_BG13.setPreferredSize(new java.awt.Dimension(600, 490));
        JD_Eliminar_Vehiculo.getContentPane().add(JD_CP_BG13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        JD_Listar_Profesor.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_Listar_Profesor.setResizable(false);
        JD_Listar_Profesor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator26.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator26.setForeground(new java.awt.Color(177, 147, 130));
        JD_Listar_Profesor.getContentPane().add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(214, 188, 164));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Listar Profesores");
        JD_Listar_Profesor.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        LP_TB_Profesores.setBackground(new java.awt.Color(51, 42, 36));
        LP_TB_Profesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        LP_TB_Profesores.setSelectionBackground(new java.awt.Color(177, 147, 130));
        LP_TB_Profesores.setSelectionForeground(new java.awt.Color(51, 51, 51));
        LP_TB_Profesores.getTableHeader().setReorderingAllowed(false);
        LP_ScrollPane.setViewportView(LP_TB_Profesores);

        JD_Listar_Profesor.getContentPane().add(LP_ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 560, 380));

        JD_CP_BG18.setBackground(new java.awt.Color(51, 42, 36));
        JD_CP_BG18.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG18.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG18.setOpaque(true);
        JD_CP_BG18.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Listar_Profesor.getContentPane().add(JD_CP_BG18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG19.setBackground(new java.awt.Color(79, 66, 57));
        JD_CP_BG19.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG19.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG19.setOpaque(true);
        JD_CP_BG19.setPreferredSize(new java.awt.Dimension(600, 520));
        JD_Listar_Profesor.getContentPane().add(JD_CP_BG19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        JD_Listar_Alumno.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_Listar_Alumno.setResizable(false);
        JD_Listar_Alumno.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator27.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator27.setForeground(new java.awt.Color(177, 147, 130));
        JD_Listar_Alumno.getContentPane().add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 161, 101));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Listar Alumnos");
        JD_Listar_Alumno.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        LP_TB_Alumnos.setBackground(new java.awt.Color(51, 42, 36));
        LP_TB_Alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Correo", "Licencias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LP_TB_Alumnos.setSelectionBackground(new java.awt.Color(255, 161, 101));
        LP_TB_Alumnos.setSelectionForeground(new java.awt.Color(51, 51, 51));
        LP_TB_Alumnos.getTableHeader().setReorderingAllowed(false);
        LP_ScrollPane1.setViewportView(LP_TB_Alumnos);
        if (LP_TB_Alumnos.getColumnModel().getColumnCount() > 0) {
            LP_TB_Alumnos.getColumnModel().getColumn(0).setResizable(false);
            LP_TB_Alumnos.getColumnModel().getColumn(1).setResizable(false);
            LP_TB_Alumnos.getColumnModel().getColumn(2).setResizable(false);
            LP_TB_Alumnos.getColumnModel().getColumn(2).setHeaderValue("Correo");
            LP_TB_Alumnos.getColumnModel().getColumn(3).setResizable(false);
        }

        JD_Listar_Alumno.getContentPane().add(LP_ScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 560, 380));

        JD_CP_BG20.setBackground(new java.awt.Color(51, 42, 36));
        JD_CP_BG20.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG20.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG20.setOpaque(true);
        JD_CP_BG20.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Listar_Alumno.getContentPane().add(JD_CP_BG20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG21.setBackground(new java.awt.Color(175, 69, 0));
        JD_CP_BG21.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG21.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG21.setOpaque(true);
        JD_CP_BG21.setPreferredSize(new java.awt.Dimension(600, 520));
        JD_Listar_Alumno.getContentPane().add(JD_CP_BG21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        JD_Listar_Vehiculo.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_Listar_Vehiculo.setResizable(false);
        JD_Listar_Vehiculo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator28.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator28.setForeground(new java.awt.Color(255, 0, 0));
        JD_Listar_Vehiculo.getContentPane().add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(232, 137, 137));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Listar Vehiculos");
        JD_Listar_Vehiculo.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 40));

        LP_TB_Vehiculos.setBackground(new java.awt.Color(51, 0, 0));
        LP_TB_Vehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Modelo", "Marca", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LP_TB_Vehiculos.setSelectionBackground(new java.awt.Color(255, 0, 0));
        LP_TB_Vehiculos.setSelectionForeground(new java.awt.Color(51, 51, 51));
        LP_TB_Vehiculos.getTableHeader().setReorderingAllowed(false);
        LP_ScrollPane2.setViewportView(LP_TB_Vehiculos);
        if (LP_TB_Vehiculos.getColumnModel().getColumnCount() > 0) {
            LP_TB_Vehiculos.getColumnModel().getColumn(0).setResizable(false);
            LP_TB_Vehiculos.getColumnModel().getColumn(1).setResizable(false);
            LP_TB_Vehiculos.getColumnModel().getColumn(2).setResizable(false);
            LP_TB_Vehiculos.getColumnModel().getColumn(3).setResizable(false);
        }

        JD_Listar_Vehiculo.getContentPane().add(LP_ScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 560, 380));

        JD_CP_BG22.setBackground(new java.awt.Color(51, 0, 0));
        JD_CP_BG22.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG22.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG22.setOpaque(true);
        JD_CP_BG22.setPreferredSize(new java.awt.Dimension(600, 400));
        JD_Listar_Vehiculo.getContentPane().add(JD_CP_BG22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        JD_CP_BG23.setBackground(new java.awt.Color(132, 11, 11));
        JD_CP_BG23.setMaximumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG23.setMinimumSize(new java.awt.Dimension(600, 400));
        JD_CP_BG23.setOpaque(true);
        JD_CP_BG23.setPreferredSize(new java.awt.Dimension(600, 520));
        JD_Listar_Vehiculo.getContentPane().add(JD_CP_BG23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TB_Pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estudiante DNI", "Descripcion", "Costo", "Pagado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TB_Pagos);
        if (TB_Pagos.getColumnModel().getColumnCount() > 0) {
            TB_Pagos.getColumnModel().getColumn(0).setResizable(false);
            TB_Pagos.getColumnModel().getColumn(1).setResizable(false);
            TB_Pagos.getColumnModel().getColumn(2).setResizable(false);
            TB_Pagos.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 580, 380));

        JD_RegistroPagos.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TB_Calificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estudiante DNI", "Profesor DNI", "Tipo", "Calificacion Obtenida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TB_Calificaciones);
        if (TB_Calificaciones.getColumnModel().getColumnCount() > 0) {
            TB_Calificaciones.getColumnModel().getColumn(0).setResizable(false);
            TB_Calificaciones.getColumnModel().getColumn(1).setResizable(false);
            TB_Calificaciones.getColumnModel().getColumn(2).setResizable(false);
            TB_Calificaciones.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 580, 380));

        JD_RegistroCalificaciones.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(90, 50));
        setMinimumSize(new java.awt.Dimension(1450, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1450, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CRUD_BG.setBackground(new java.awt.Color(43, 43, 43));
        CRUD_BG.setMinimumSize(new java.awt.Dimension(1450, 700));
        CRUD_BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator14.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator14.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator14.setOpaque(true);
        CRUD_BG.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 20, 190));

        jSeparator15.setBackground(new java.awt.Color(204, 127, 0));
        jSeparator15.setForeground(new java.awt.Color(204, 127, 0));
        jSeparator15.setOpaque(true);
        CRUD_BG.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 20, 190));

        jSeparator16.setBackground(new java.awt.Color(177, 147, 130));
        jSeparator16.setForeground(new java.awt.Color(177, 147, 130));
        jSeparator16.setOpaque(true);
        CRUD_BG.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 190));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator11.setForeground(new java.awt.Color(255, 0, 0));
        CRUD_BG.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 1420, 10));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator10.setForeground(new java.awt.Color(177, 147, 130));
        CRUD_BG.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1420, 10));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator9.setForeground(new java.awt.Color(204, 127, 0));
        CRUD_BG.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1420, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator5.setForeground(new java.awt.Color(255, 0, 0));
        CRUD_BG.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 300, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator6.setForeground(new java.awt.Color(204, 127, 0));
        CRUD_BG.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 300, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator7.setForeground(new java.awt.Color(177, 147, 130));
        CRUD_BG.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 300, 10));

        BT_Listar_Profesor.setBackground(new java.awt.Color(91, 80, 28));
        BT_Listar_Profesor.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Listar_Profesor.setText("Listar");
        BT_Listar_Profesor.setBorderPainted(false);
        BT_Listar_Profesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Listar_Profesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Listar_ProfesorMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Listar_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 250, 70));

        BT_Listar_Alumno.setBackground(new java.awt.Color(91, 80, 28));
        BT_Listar_Alumno.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Listar_Alumno.setText("Listar");
        BT_Listar_Alumno.setBorderPainted(false);
        BT_Listar_Alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Listar_Alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Listar_AlumnoMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Listar_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 250, 70));

        BT_Listar_Vehiculo.setBackground(new java.awt.Color(91, 80, 28));
        BT_Listar_Vehiculo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Listar_Vehiculo.setText("Listar");
        BT_Listar_Vehiculo.setBorderPainted(false);
        BT_Listar_Vehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Listar_Vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Listar_VehiculoMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Listar_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 250, 70));

        BT_Crear_Profesor.setBackground(new java.awt.Color(29, 91, 49));
        BT_Crear_Profesor.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Crear_Profesor.setText("Crear");
        BT_Crear_Profesor.setBorderPainted(false);
        BT_Crear_Profesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Crear_Profesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Crear_ProfesorMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Crear_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 250, 70));

        BT_Crear_Alumno.setBackground(new java.awt.Color(29, 91, 49));
        BT_Crear_Alumno.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Crear_Alumno.setText("Crear");
        BT_Crear_Alumno.setBorderPainted(false);
        BT_Crear_Alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Crear_Alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Crear_AlumnoMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Crear_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 250, 70));

        BT_Crear_Vehiculo.setBackground(new java.awt.Color(29, 91, 49));
        BT_Crear_Vehiculo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Crear_Vehiculo.setText("Crear");
        BT_Crear_Vehiculo.setBorderPainted(false);
        BT_Crear_Vehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Crear_Vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Crear_VehiculoMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Crear_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 250, 70));

        BT_Modificar_Profesor.setBackground(new java.awt.Color(40, 77, 119));
        BT_Modificar_Profesor.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Modificar_Profesor.setText("Modificar");
        BT_Modificar_Profesor.setBorderPainted(false);
        BT_Modificar_Profesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Modificar_Profesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Modificar_ProfesorMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Modificar_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 250, 70));

        BT_Modificar_Alumno.setBackground(new java.awt.Color(40, 77, 119));
        BT_Modificar_Alumno.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Modificar_Alumno.setText("Modificar");
        BT_Modificar_Alumno.setBorderPainted(false);
        BT_Modificar_Alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Modificar_Alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Modificar_AlumnoMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Modificar_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 250, 70));

        BT_Modificar_Vehiculo.setBackground(new java.awt.Color(40, 77, 119));
        BT_Modificar_Vehiculo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Modificar_Vehiculo.setText("Modificar");
        BT_Modificar_Vehiculo.setBorderPainted(false);
        BT_Modificar_Vehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Modificar_Vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Modificar_VehiculoMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Modificar_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, 250, 70));

        BT_Eliminar_Profesor.setBackground(new java.awt.Color(99, 32, 39));
        BT_Eliminar_Profesor.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Eliminar_Profesor.setText("Eliminar");
        BT_Eliminar_Profesor.setBorderPainted(false);
        BT_Eliminar_Profesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Eliminar_Profesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Eliminar_ProfesorMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Eliminar_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 80, 250, 70));

        BT_Eliminar_Alumno.setBackground(new java.awt.Color(99, 32, 39));
        BT_Eliminar_Alumno.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Eliminar_Alumno.setText("Eliminar");
        BT_Eliminar_Alumno.setBorderPainted(false);
        BT_Eliminar_Alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Eliminar_Alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Eliminar_AlumnoMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Eliminar_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 290, 250, 70));

        BT_Eliminar_Vehiculo.setBackground(new java.awt.Color(99, 32, 39));
        BT_Eliminar_Vehiculo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        BT_Eliminar_Vehiculo.setText("Eliminar");
        BT_Eliminar_Vehiculo.setBorderPainted(false);
        BT_Eliminar_Vehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Eliminar_Vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_Eliminar_VehiculoMousePressed(evt);
            }
        });
        CRUD_BG.add(BT_Eliminar_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 510, 250, 70));

        jSeparator2.setBackground(new java.awt.Color(255, 161, 101));
        jSeparator2.setForeground(new java.awt.Color(255, 161, 101));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);
        CRUD_BG.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 20, 190));

        jSeparator3.setBackground(new java.awt.Color(232, 137, 137));
        jSeparator3.setForeground(new java.awt.Color(232, 137, 137));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setOpaque(true);
        CRUD_BG.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 20, 190));

        jSeparator4.setBackground(new java.awt.Color(214, 188, 164));
        jSeparator4.setForeground(new java.awt.Color(214, 188, 164));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setOpaque(true);
        CRUD_BG.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 190));

        BT_RegistrosCalificaciones.setText("Ver Registro de Calificaciones");
        BT_RegistrosCalificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_RegistrosCalificacionesMousePressed(evt);
            }
        });
        BT_RegistrosCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_RegistrosCalificacionesActionPerformed(evt);
            }
        });
        CRUD_BG.add(BT_RegistrosCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 180, -1));

        BT_RegistrosPagos.setText("Ver Registros de Pagos");
        BT_RegistrosPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_RegistrosPagosMousePressed(evt);
            }
        });
        BT_RegistrosPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_RegistrosPagosActionPerformed(evt);
            }
        });
        CRUD_BG.add(BT_RegistrosPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 180, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(232, 137, 137));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Vehículos");
        jLabel8.setToolTipText("");
        CRUD_BG.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 1420, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 161, 101));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Estudiantes");
        jLabel2.setToolTipText("");
        CRUD_BG.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 1420, -1));

        jLabel7.setBackground(new java.awt.Color(51, 40, 30));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(214, 188, 164));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Profesores");
        jLabel7.setToolTipText("");
        CRUD_BG.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1420, -1));

        jLabel3.setBackground(new java.awt.Color(51, 40, 30));
        jLabel3.setOpaque(true);
        CRUD_BG.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1420, 190));

        jLabel4.setBackground(new java.awt.Color(160, 63, 0));
        jLabel4.setOpaque(true);
        CRUD_BG.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1420, 190));

        jLabel5.setBackground(new java.awt.Color(132, 11, 11));
        jLabel5.setOpaque(true);
        CRUD_BG.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 1420, 190));

        getContentPane().add(CRUD_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CP_BT_CrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CP_BT_CrearMousePressed
        String DNI = CP_TF_DNI.getText();
        String Nombre = CP_TF_Nombre.getText();
        String Correo = CP_TF_Correo.getText();
        String ensenia = CP_CB_LicenciaEnseniar.getSelectedItem().toString();
        String contra = CP_TF_Password.getText();
        Document doc = new Document("dni", DNI);
        doc.append("nombre", Nombre);
        doc.append("correo", Correo);
        doc.append("ensenia", ensenia);
        doc.append("contra", contra);
        conn.profesores.insertOne(doc);
        CP_TF_DNI.setText("");
        CP_TF_Nombre.setText("");
        CP_TF_Correo.setText("");
        CP_TF_Password.setText("");
        JOptionPane.showMessageDialog(JD_Crear_Profesor, "Profesor creado correctamente");
    }//GEN-LAST:event_CP_BT_CrearMousePressed

    private void EP_BT_EliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EP_BT_EliminarMousePressed
        if(EP_CB_Profesor.getSelectedIndex() >= 0){
            int i = EP_CB_Profesor.getSelectedIndex();
            Document dc = new Document("dni",profesoresdni.get(i));
            conn.profesores.deleteOne(dc);
            conn.profesores.deleteMany(new Document("profesor_dni", profesoresdni.get(i)));
            JOptionPane.showMessageDialog(JD_Eliminar_Profesor, "Se elimino con exito");
            BT_Eliminar_ProfesorMousePressed(evt);
        }
    }//GEN-LAST:event_EP_BT_EliminarMousePressed

    private void CP_CB_LicenciaEnseniarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CP_CB_LicenciaEnseniarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CP_CB_LicenciaEnseniarActionPerformed

    private void MP_BT_ModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MP_BT_ModificarMousePressed
        if(MP_CB_Profesor.getSelectedIndex() >= 0){
            int i = MP_CB_Profesor.getSelectedIndex();
            Document df = new Document("dni", profesoresdni.get(i));
            Document dm = new Document("correo", MP_TF_Correo.getText());
            dm.append("contra", MP_TF_Password.getText());
            dm.append("ensenia", (String)MP_CB_LicenciaEnseniar.getSelectedItem());
            conn.profesores.updateOne(df, new Document("$set",dm));
            JOptionPane.showMessageDialog(JD_Modificar_Profesor, "Se modifico exitosamente");
        }
    }//GEN-LAST:event_MP_BT_ModificarMousePressed

    private void MP_CB_ProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MP_CB_ProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MP_CB_ProfesorActionPerformed

    private void MP_CB_LicenciaEnseniarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MP_CB_LicenciaEnseniarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MP_CB_LicenciaEnseniarActionPerformed

    private void EA_BT_EliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EA_BT_EliminarMousePressed
        if(EA_CB_Alumno.getSelectedIndex() >= 0){
            int i = EA_CB_Alumno.getSelectedIndex();
            Document dc = new Document("dni",estudiantesdni.get(i));
            conn.estudiantes.deleteOne(dc);
            conn.practicas.deleteMany(new Document("alumno_dni",estudiantesdni.get(i)));
            JOptionPane.showMessageDialog(JD_Eliminar_Alumno, "Se elimino con exito");
            BT_Eliminar_AlumnoMousePressed(evt);
        }
    }//GEN-LAST:event_EA_BT_EliminarMousePressed

    private void CA_BT_CrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CA_BT_CrearMousePressed
        String nombre = CA_TF_Nombre.getText();
        String DNI = CA_TF_DNI.getText();
        String correo = CA_TF_Correo.getText();
        String contra = CA_TF_Password.getText();
        Document doc = new Document("dni", DNI);
        doc.append("nombre", nombre);
        doc.append("correo", correo);
        doc.append("contra", contra);
        ArrayList<Document> doc2 = new ArrayList<Document>();
        doc.append("licencias", doc2);
        conn.estudiantes.insertOne(doc);
        CA_TF_Nombre.setText("");
        CA_TF_DNI.setText("");
        CA_TF_Correo.setText("");
        CA_TF_Password.setText("");
        JOptionPane.showMessageDialog(JD_Crear_Alumno, "Estudiante Creado");
    }//GEN-LAST:event_CA_BT_CrearMousePressed

    private void MA_BT_ModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MA_BT_ModificarMousePressed
        if(MA_CB_Alumno.getSelectedIndex() >= 0){
            int i = MA_CB_Alumno.getSelectedIndex();
            Document df = new Document("dni", estudiantesdni.get(i));
            Document dm = new Document("correo", MA_TF_Correo.getText());
            dm.append("contra", MA_TF_Password.getText());
            conn.estudiantes.updateOne(df, new Document("$set", dm));
            JOptionPane.showMessageDialog(JD_Modificar_Alumno, "Se modifico exitosamente");
        }
    }//GEN-LAST:event_MA_BT_ModificarMousePressed

    private void MA_CB_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MA_CB_AlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MA_CB_AlumnoActionPerformed

    private void EV_BT_EliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EV_BT_EliminarMousePressed
        if(EV_CB_Vehiculo.getSelectedIndex() >= 0 && vehiculosmatriculas.size() > 0){
            int i = EV_CB_Vehiculo.getSelectedIndex();
            Document dc = new Document("matricula",vehiculosmatriculas.get(i));
            conn.vehiculos.deleteOne(dc);
            JOptionPane.showMessageDialog(JD_Eliminar_Vehiculo, "Se elimino con exito");
            BT_Eliminar_VehiculoMousePressed(evt);
        }
    }//GEN-LAST:event_EV_BT_EliminarMousePressed

    private void CV_BT_CrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CV_BT_CrearMousePressed
        String matricula = CV_TF_Matricula.getText();
        String modelo = CV_TF_Modelo.getText();
        String marca = CV_TF_Marca.getText();
        String tarifa = CV_SP_Tarifa.getValue().toString();
        float tar = Float.parseFloat(tarifa);
        Document doc = new Document("matricula", matricula);
        doc.append("modelo", modelo);
        doc.append("marca", marca);
        doc.append("tarifa", tar);
        doc.append("profesor", profesoresdni.get(CV_CB_Profesor.getSelectedIndex()));
        doc.append("kilometraje", 0);
        conn.vehiculos.insertOne(doc);
        CV_TF_Matricula.setText("");
        CV_TF_Modelo.setText("");
        CV_TF_Marca.setText("");
        CV_SP_Tarifa.setValue(0);
        JOptionPane.showMessageDialog(JD_Crear_Vehiculo, "Vehiculo Creado");
    }//GEN-LAST:event_CV_BT_CrearMousePressed

    private void MV_BT_ModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MV_BT_ModificarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MV_BT_ModificarMousePressed

    private void MV_CB_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MV_CB_VehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MV_CB_VehiculoActionPerformed

    private void BT_Eliminar_VehiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Eliminar_VehiculoMousePressed
        vehiculosmatriculas.clear();
        MongoCursor<Document> cursor = conn.vehiculos.find().iterator();
        EV_CB_Vehiculo.removeAllItems();
        while(cursor.hasNext()){
            Document dc = cursor.next();
            EV_CB_Vehiculo.addItem(dc.get("matricula") + " | " + dc.get("marca") + " " +  dc.get("modelo"));
            vehiculosmatriculas.add((String)dc.get("matricula"));
        }
        Abrir_JDialog(JD_Eliminar_Vehiculo);
    }//GEN-LAST:event_BT_Eliminar_VehiculoMousePressed

    private void BT_Eliminar_AlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Eliminar_AlumnoMousePressed
        estudiantesdni.clear();
        MongoCursor<Document> cursor = conn.estudiantes.find().iterator();
        EA_CB_Alumno.removeAllItems();
        while(cursor.hasNext()){
            Document dc = cursor.next();
            EA_CB_Alumno.addItem(dc.get("dni") + " | " + dc.get("nombre"));
            estudiantesdni.add((String)dc.get("dni"));
        }
        Abrir_JDialog(JD_Eliminar_Alumno);
    }//GEN-LAST:event_BT_Eliminar_AlumnoMousePressed

    private void BT_Eliminar_ProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Eliminar_ProfesorMousePressed
        profesoresdni.clear();
        MongoCursor<Document> cursor = conn.profesores.find().iterator();
        EP_CB_Profesor.removeAllItems();
        while(cursor.hasNext()){
            Document dc = cursor.next();
            EP_CB_Profesor.addItem(dc.get("dni") + " | " + dc.get("nombre"));
            profesoresdni.add((String)dc.get("dni"));
        }
        Abrir_JDialog(JD_Eliminar_Profesor);
    }//GEN-LAST:event_BT_Eliminar_ProfesorMousePressed

    private void BT_Modificar_AlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Modificar_AlumnoMousePressed
        estudiantesdni.clear();
        MongoCursor<Document> cursor = conn.estudiantes.find().iterator();
        MA_CB_Alumno.removeAllItems();
        while(cursor.hasNext()){
            Document dc = cursor.next();
            MA_CB_Alumno.addItem(dc.get("dni") + " | " + dc.get("nombre"));
            estudiantesdni.add((String)dc.get("dni"));
        }
        Abrir_JDialog(JD_Modificar_Alumno);
    }//GEN-LAST:event_BT_Modificar_AlumnoMousePressed

    private void BT_Modificar_ProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Modificar_ProfesorMousePressed
        profesoresdni.clear();
        MongoCursor<Document> cursor = conn.profesores.find().iterator();
        MP_CB_Profesor.removeAllItems();
        while(cursor.hasNext()){
            Document dc = cursor.next();
            MP_CB_Profesor.addItem(dc.get("dni") + " | " + dc.get("nombre"));
            profesoresdni.add((String)dc.get("dni"));
        }
        Abrir_JDialog(JD_Modificar_Profesor);
    }//GEN-LAST:event_BT_Modificar_ProfesorMousePressed

    private void BT_Crear_VehiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Crear_VehiculoMousePressed
        profesoresdni.clear();
        MongoCursor<Document> cursor = conn.profesores.find().iterator();
        CV_CB_Profesor.removeAllItems();
        while(cursor.hasNext()){
            Document dc = cursor.next();
            CV_CB_Profesor.addItem(dc.get("dni") + " | " + dc.get("nombre"));
            profesoresdni.add((String)dc.get("dni"));
        }   
        Abrir_JDialog(JD_Crear_Vehiculo);
    }//GEN-LAST:event_BT_Crear_VehiculoMousePressed

    private void BT_Crear_AlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Crear_AlumnoMousePressed
        Abrir_JDialog(JD_Crear_Alumno);
    }//GEN-LAST:event_BT_Crear_AlumnoMousePressed

    private void BT_Crear_ProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Crear_ProfesorMousePressed
        Abrir_JDialog(JD_Crear_Profesor);
    }//GEN-LAST:event_BT_Crear_ProfesorMousePressed

    private void BT_Listar_VehiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Listar_VehiculoMousePressed
        MongoCursor<Document> cursor = conn.vehiculos.find().iterator();
        DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new String[]{"Matricula","Modelo","Marca","Tarifa", "Profesor", "Kilometraje"});
        while(cursor.hasNext()){
            Document dc = cursor.next();
            Object row[] = {
                dc.get("matricula"),
                dc.get("modelo"),
                dc.get("marca"),
                dc.get("tarifa"),
                dc.get("profesor"),
                dc.get("kilometraje")
            };
            model.addRow(row);
        }
        LP_TB_Vehiculos.setModel(model);
        Abrir_JDialog(JD_Listar_Vehiculo);
    }//GEN-LAST:event_BT_Listar_VehiculoMousePressed

    private void BT_Listar_AlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Listar_AlumnoMousePressed
        MongoCursor<Document> cursor = conn.estudiantes.find().iterator();
        DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new String[]{"DNI","Nombre","Correo","Licencias"});
        while(cursor.hasNext()){
            Document dc = cursor.next();
            String lic = "";
            ArrayList<Document> licencias = (ArrayList<Document>)dc.get("licencias");
            for(Document licencia : licencias)
                lic += licencia.get("tipo") + ", ";
            Object row[] = {
                dc.get("dni"),
                dc.get("nombre"),
                dc.get("correo"),
                lic
            };
            model.addRow(row);
        }
        LP_TB_Alumnos.setModel(model);        
        Abrir_JDialog(JD_Listar_Alumno);
    }//GEN-LAST:event_BT_Listar_AlumnoMousePressed

    private void BT_Listar_ProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Listar_ProfesorMousePressed
        MongoCursor<Document> cursor = conn.profesores.find().iterator();
        DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new String[]{"DNI","Nombre","Correo","Enseña"});
        while(cursor.hasNext()){
           Document dc = cursor.next();
           Object row[] = {
                dc.get("dni"),
                dc.get("nombre"),
                dc.get("correo"),
                dc.get("ensenia")
           };
           model.addRow(row);
        }
        LP_TB_Profesores.setModel(model);
        Abrir_JDialog(JD_Listar_Profesor);
    }//GEN-LAST:event_BT_Listar_ProfesorMousePressed

    private void CV_BT_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CV_BT_CrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CV_BT_CrearActionPerformed

    private void CV_CB_ProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CV_CB_ProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CV_CB_ProfesorActionPerformed

    private void MP_CB_ProfesorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MP_CB_ProfesorItemStateChanged
        if(MP_CB_Profesor.getSelectedIndex() >= 0 && !profesoresdni.isEmpty()){
            String dni = profesoresdni.get(MP_CB_Profesor.getSelectedIndex());
            Document df = new Document("dni",dni);
            MongoCursor<Document> dc = conn.profesores.find(df).iterator();
            Document d = dc.next();
            MP_TF_Correo.setText((String)d.get("correo"));
            MP_TF_Password.setText((String)d.get("contra"));
            MP_CB_LicenciaEnseniar.setSelectedItem((String)d.get("ensenia"));
        }
    }//GEN-LAST:event_MP_CB_ProfesorItemStateChanged

    private void BT_Modificar_VehiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Modificar_VehiculoMousePressed
        Abrir_JDialog(JD_Modificar_Vehiculo);
    }//GEN-LAST:event_BT_Modificar_VehiculoMousePressed

    private void BT_RegistrosPagosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_RegistrosPagosMousePressed
        ArrayList<Document> coso = new ArrayList<>();
        conn.pagos.find().into(coso);
        DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new Object[]{"Estudiante DNI", "Descripcion", "Costo", "Pagado"});
        for(Document p : coso){
            Object[] row = {
                p.get("alumno_dni"),p.get("descripcion"), p.get("costo"), p.get("pagado")
            };
            model.addRow(row);
        }
        TB_Pagos.setModel(model);
        Abrir_JDialog(JD_RegistroPagos);
    }//GEN-LAST:event_BT_RegistrosPagosMousePressed

    private void BT_RegistrosPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_RegistrosPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_RegistrosPagosActionPerformed

    private void BT_RegistrosCalificacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_RegistrosCalificacionesMousePressed
        ArrayList<Document> coso = new ArrayList<>();
        conn.calificaciones.find().into(coso);
        DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new Object[]{"Estudiante DNI", "Profesor DNI", "Tipo", "Calificacion"});
        for(Document p : coso){
            Object[] row = {
                p.get("alumno_dni"),p.get("profesor_dni"), p.get("tipo"), p.get("Calificacion Obtenida")
            };
            model.addRow(row);
        }
        TB_Calificaciones.setModel(model);
        Abrir_JDialog(JD_RegistroCalificaciones);        
    }//GEN-LAST:event_BT_RegistrosCalificacionesMousePressed

    private void BT_RegistrosCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_RegistrosCalificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_RegistrosCalificacionesActionPerformed

    private void MA_CB_AlumnoItemStateChanged(java.awt.event.ItemEvent evt){
        if(MA_CB_Alumno.getSelectedIndex() >= 0 && !estudiantesdni.isEmpty()){
            String dni = estudiantesdni.get(MA_CB_Alumno.getSelectedIndex());
            Document df = new Document("dni",dni);
            MongoCursor<Document> dc = conn.estudiantes.find(df).iterator();
            Document d = dc.next();
            MA_TF_Correo.setText((String)d.get("correo"));
            MA_TF_Password.setText((String)d.get("contra"));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Crear_Alumno;
    private javax.swing.JButton BT_Crear_Profesor;
    private javax.swing.JButton BT_Crear_Vehiculo;
    private javax.swing.JButton BT_Eliminar_Alumno;
    private javax.swing.JButton BT_Eliminar_Profesor;
    private javax.swing.JButton BT_Eliminar_Vehiculo;
    private javax.swing.JButton BT_Listar_Alumno;
    private javax.swing.JButton BT_Listar_Profesor;
    private javax.swing.JButton BT_Listar_Vehiculo;
    private javax.swing.JButton BT_Modificar_Alumno;
    private javax.swing.JButton BT_Modificar_Profesor;
    private javax.swing.JButton BT_Modificar_Vehiculo;
    private javax.swing.JButton BT_RegistrosCalificaciones;
    private javax.swing.JButton BT_RegistrosPagos;
    private javax.swing.JButton CA_BT_Crear;
    private javax.swing.JTextField CA_TF_Correo;
    private javax.swing.JTextField CA_TF_DNI;
    private javax.swing.JTextField CA_TF_Nombre;
    private javax.swing.JTextField CA_TF_Password;
    private javax.swing.JButton CP_BT_Crear;
    private javax.swing.JComboBox<String> CP_CB_LicenciaEnseniar;
    private javax.swing.JTextField CP_TF_Correo;
    private javax.swing.JTextField CP_TF_DNI;
    private javax.swing.JTextField CP_TF_Nombre;
    private javax.swing.JTextField CP_TF_Password;
    private javax.swing.JPanel CRUD_BG;
    private javax.swing.JButton CV_BT_Crear;
    private javax.swing.JComboBox<String> CV_CB_Profesor;
    private javax.swing.JSpinner CV_SP_Tarifa;
    private javax.swing.JTextField CV_TF_Marca;
    private javax.swing.JTextField CV_TF_Matricula;
    private javax.swing.JTextField CV_TF_Modelo;
    private javax.swing.JButton EA_BT_Eliminar;
    private javax.swing.JComboBox<String> EA_CB_Alumno;
    private javax.swing.JButton EP_BT_Eliminar;
    private javax.swing.JComboBox<String> EP_CB_Profesor;
    private javax.swing.JButton EV_BT_Eliminar;
    private javax.swing.JComboBox<String> EV_CB_Vehiculo;
    private javax.swing.JLabel JD_CP_BG;
    private javax.swing.JLabel JD_CP_BG1;
    private javax.swing.JLabel JD_CP_BG10;
    private javax.swing.JLabel JD_CP_BG11;
    private javax.swing.JLabel JD_CP_BG12;
    private javax.swing.JLabel JD_CP_BG13;
    private javax.swing.JLabel JD_CP_BG14;
    private javax.swing.JLabel JD_CP_BG15;
    private javax.swing.JLabel JD_CP_BG16;
    private javax.swing.JLabel JD_CP_BG17;
    private javax.swing.JLabel JD_CP_BG18;
    private javax.swing.JLabel JD_CP_BG19;
    private javax.swing.JLabel JD_CP_BG2;
    private javax.swing.JLabel JD_CP_BG20;
    private javax.swing.JLabel JD_CP_BG21;
    private javax.swing.JLabel JD_CP_BG22;
    private javax.swing.JLabel JD_CP_BG23;
    private javax.swing.JLabel JD_CP_BG3;
    private javax.swing.JLabel JD_CP_BG4;
    private javax.swing.JLabel JD_CP_BG5;
    private javax.swing.JLabel JD_CP_BG6;
    private javax.swing.JLabel JD_CP_BG7;
    private javax.swing.JLabel JD_CP_BG8;
    private javax.swing.JLabel JD_CP_BG9;
    private javax.swing.JDialog JD_Crear_Alumno;
    private javax.swing.JDialog JD_Crear_Profesor;
    private javax.swing.JDialog JD_Crear_Vehiculo;
    private javax.swing.JDialog JD_Eliminar_Alumno;
    private javax.swing.JDialog JD_Eliminar_Profesor;
    private javax.swing.JDialog JD_Eliminar_Vehiculo;
    private javax.swing.JDialog JD_Listar_Alumno;
    private javax.swing.JDialog JD_Listar_Profesor;
    private javax.swing.JDialog JD_Listar_Vehiculo;
    private javax.swing.JDialog JD_Modificar_Alumno;
    private javax.swing.JDialog JD_Modificar_Profesor;
    private javax.swing.JDialog JD_Modificar_Vehiculo;
    private javax.swing.JDialog JD_RegistroCalificaciones;
    private javax.swing.JDialog JD_RegistroPagos;
    private javax.swing.JScrollPane LP_ScrollPane;
    private javax.swing.JScrollPane LP_ScrollPane1;
    private javax.swing.JScrollPane LP_ScrollPane2;
    private javax.swing.JTable LP_TB_Alumnos;
    private javax.swing.JTable LP_TB_Profesores;
    private javax.swing.JTable LP_TB_Vehiculos;
    private javax.swing.JButton MA_BT_Modificar;
    private javax.swing.JComboBox<String> MA_CB_Alumno;
    private javax.swing.JTextField MA_TF_Correo;
    private javax.swing.JTextField MA_TF_Password;
    private javax.swing.JButton MP_BT_Modificar;
    private javax.swing.JComboBox<String> MP_CB_LicenciaEnseniar;
    private javax.swing.JComboBox<String> MP_CB_Profesor;
    private javax.swing.JTextField MP_TF_Correo;
    private javax.swing.JTextField MP_TF_Password;
    private javax.swing.JButton MV_BT_Modificar;
    private javax.swing.JComboBox<String> MV_CB_Estado;
    private javax.swing.JComboBox<String> MV_CB_Vehiculo;
    private javax.swing.JSpinner MV_SP_Tarifa;
    private javax.swing.JTextField MV_TF_Marca;
    private javax.swing.JTextField MV_TF_Matricula;
    private javax.swing.JTextField MV_TF_Modelo;
    private javax.swing.JTable TB_Calificaciones;
    private javax.swing.JTable TB_Pagos;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables

    private void Abrir_JDialog(JDialog JD) {
        JD.setModal(true);
        JD.pack();
        JD.setLocationRelativeTo(null);//this Frame
        JD.setVisible(true);
    }
    
    private ArrayList<String> profesoresdni = new ArrayList<>();
    private ArrayList<String> estudiantesdni = new ArrayList<>();
    private ArrayList<String> vehiculosmatriculas = new ArrayList<>();
}
