/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import com.mongodb.client.MongoCursor;
import java.awt.Color;
import org.bson.Document;

/**
 *
 * @author emili
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login_Profesor
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        L_Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        L_AccederComo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        L_Usuario = new javax.swing.JLabel();
        TF_Usuario = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        BT_Ingresar = new javax.swing.JButton();
        L_Contraseña = new javax.swing.JLabel();
        PF_Password = new javax.swing.JPasswordField();
        jSeparator9 = new javax.swing.JSeparator();
        BT_VerPassword = new javax.swing.JButton();
        Login_BG = new javax.swing.JLabel();
        Login_BG3 = new javax.swing.JLabel();
        Login_BG4 = new javax.swing.JLabel();
        Login_BG5 = new javax.swing.JLabel();
        Login_BG6 = new javax.swing.JLabel();
        Login_BG7 = new javax.swing.JLabel();
        Login_BG8 = new javax.swing.JLabel();
        Login_BG9 = new javax.swing.JLabel();
        Login_BG11 = new javax.swing.JLabel();
        Login_BG12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 102, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 11, 74));

        L_Titulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 55)); // NOI18N
        L_Titulo.setForeground(new java.awt.Color(204, 204, 204));
        L_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Titulo.setText("Iniciar Sesión");
        getContentPane().add(L_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 360, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setOpaque(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 11, 74));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acceder como");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 210, -1));

        L_AccederComo.setBackground(new java.awt.Color(43, 43, 43));
        L_AccederComo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        L_AccederComo.setForeground(new java.awt.Color(0, 102, 255));
        L_AccederComo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_AccederComo.setText("Administrador");
        L_AccederComo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L_AccederComo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_AccederComoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L_AccederComoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L_AccederComoMouseExited(evt);
            }
        });
        getContentPane().add(L_AccederComo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 210, 40));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 80, 80));

        L_Usuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        L_Usuario.setText("Nombre de Usuario");
        getContentPane().add(L_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        TF_Usuario.setBackground(new java.awt.Color(33, 33, 33));
        TF_Usuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
        TF_Usuario.setForeground(java.awt.Color.darkGray);
        TF_Usuario.setText("Ingrese su nombre de usuario");
        TF_Usuario.setActionCommand("<Not Set>");
        TF_Usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33)));
        TF_Usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TF_UsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_UsuarioFocusLost(evt);
            }
        });
        TF_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TF_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(TF_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 370, 31));

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, 50));

        BT_Ingresar.setBackground(new java.awt.Color(0, 0, 204));
        BT_Ingresar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        BT_Ingresar.setForeground(new java.awt.Color(193, 193, 193));
        BT_Ingresar.setText("Ingresar");
        BT_Ingresar.setBorderPainted(false);
        BT_Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BT_IngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BT_IngresarMouseExited(evt);
            }
        });
        BT_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 330, 40));

        L_Contraseña.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        L_Contraseña.setText("Contraseña");
        getContentPane().add(L_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        PF_Password.setBackground(new java.awt.Color(33, 33, 33));
        PF_Password.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
        PF_Password.setForeground(java.awt.Color.white);
        PF_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33)));
        PF_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PF_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PF_PasswordFocusLost(evt);
            }
        });
        PF_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF_PasswordActionPerformed(evt);
            }
        });
        PF_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PF_PasswordKeyPressed(evt);
            }
        });
        getContentPane().add(PF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 330, 31));

        jSeparator9.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, 50));

        BT_VerPassword.setBackground(new java.awt.Color(12, 12, 12));
        BT_VerPassword.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        BT_VerPassword.setForeground(new java.awt.Color(0, 91, 229));
        BT_VerPassword.setText("<O>");
        BT_VerPassword.setToolTipText("Ver Contraseña");
        BT_VerPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33)));
        BT_VerPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_VerPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_VerPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BT_VerPasswordMouseReleased(evt);
            }
        });
        BT_VerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_VerPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(BT_VerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 40, 31));

        Login_BG.setBackground(new java.awt.Color(0, 0, 0));
        Login_BG.setOpaque(true);
        getContentPane().add(Login_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 720, 620));

        Login_BG3.setBackground(new java.awt.Color(0, 102, 255));
        Login_BG3.setOpaque(true);
        getContentPane().add(Login_BG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 620));

        Login_BG4.setBackground(new java.awt.Color(0, 91, 229));
        Login_BG4.setOpaque(true);
        getContentPane().add(Login_BG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 50, 620));

        Login_BG5.setBackground(new java.awt.Color(0, 70, 178));
        Login_BG5.setOpaque(true);
        getContentPane().add(Login_BG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 50, 620));

        Login_BG6.setBackground(new java.awt.Color(0, 60, 153));
        Login_BG6.setOpaque(true);
        getContentPane().add(Login_BG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 620));

        Login_BG7.setBackground(new java.awt.Color(0, 49, 127));
        Login_BG7.setOpaque(true);
        getContentPane().add(Login_BG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 30, 620));

        Login_BG8.setBackground(new java.awt.Color(0, 39, 102));
        Login_BG8.setOpaque(true);
        getContentPane().add(Login_BG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 30, 620));

        Login_BG9.setBackground(new java.awt.Color(0, 29, 76));
        Login_BG9.setOpaque(true);
        getContentPane().add(Login_BG9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 20, 620));

        Login_BG11.setBackground(new java.awt.Color(0, 9, 25));
        Login_BG11.setOpaque(true);
        getContentPane().add(Login_BG11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 620));

        Login_BG12.setBackground(new java.awt.Color(0, 19, 51));
        Login_BG12.setOpaque(true);
        getContentPane().add(Login_BG12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 20, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_UsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_UsuarioFocusGained
        if (TF_Usuario.getText().contains("Ingrese su nombre de usuario")) {
            TF_Usuario.setForeground(Color.white);
            TF_Usuario.setText("");
        } else if (!TF_Usuario.getText().isEmpty() && !TF_Usuario.getText().contains("Ingrese su nombre de usuario")) {
            TF_Usuario.setForeground(Color.white);
        }
    }//GEN-LAST:event_TF_UsuarioFocusGained

    private void TF_UsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_UsuarioFocusLost
        if (TF_Usuario.getText().isEmpty()) {
            TF_Usuario.setForeground(Color.DARK_GRAY);
            TF_Usuario.setText("Ingrese su nombre de usuario");
        } else if (!TF_Usuario.getText().isEmpty() && !TF_Usuario.getText().contains("Ingrese su nombre de usuario")) {
            TF_Usuario.setForeground(Color.white);
        }
    }//GEN-LAST:event_TF_UsuarioFocusLost

    private void TF_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_UsuarioKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {

            PF_Password.requestFocusInWindow();

            if (PF_Password.getText().equals(" Ingrese su contraseña")) {
                PF_Password.setForeground(Color.white);
                PF_Password.setText("");
                PF_Password.setEchoChar('•');
            }
            if (TF_Usuario.getText().isEmpty()) {
                TF_Usuario.setForeground(Color.DARK_GRAY);
                TF_Usuario.setText("Ingrese su nombre de usuario");
            } else if (!TF_Usuario.getText().isEmpty() && !TF_Usuario.getText().contains("Ingrese su nombre de usuario")) {
                TF_Usuario.setForeground(Color.white);
            }
        }
    }//GEN-LAST:event_TF_UsuarioKeyPressed

    private void BT_IngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_IngresarMouseEntered
        BT_Ingresar.setBackground(new Color(0, 216, 224));
        BT_Ingresar.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_BT_IngresarMouseEntered

    private void BT_IngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_IngresarMouseExited
        BT_Ingresar.setBackground(new Color(0, 0, 204));
        BT_Ingresar.setForeground(new Color(193, 193, 193));
    }//GEN-LAST:event_BT_IngresarMouseExited

    private void BT_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_IngresarActionPerformed
        String pass = PF_Password.getText();
        String usuario = TF_Usuario.getText();

        if (L_AccederComo.getText().equals("Administrador")) {
            try {
                Document df = new Document();
                df.append("usuario", usuario);
                df.append("contra", pass);
                MongoCursor<Document> cursor = conn.administradores.find(df).iterator();
                if(cursor.hasNext()){
                    new Interfaz().setVisible(true);
                    this.dispose();   
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (L_AccederComo.getText().equals("Profesor")) {
            try {
                Document df = new Document();
                df.append("correo", usuario);
                df.append("contra", pass);
                MongoCursor<Document> cursor = conn.profesores.find(df).iterator();
                if(cursor.hasNext()){
                    new Interfaz_Profesor((String)cursor.next().get("dni")).setVisible(true);
                    this.dispose();   
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                Document df = new Document();
                df.append("correo", usuario);
                df.append("contra", pass);
                MongoCursor<Document> cursor = conn.estudiantes.find(df).iterator();
                if(cursor.hasNext()){
                    new Interfaz_Alumno((String)cursor.next().get("dni")).setVisible(true);
                    this.dispose();   
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_BT_IngresarActionPerformed

    private void PF_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PF_PasswordFocusGained
        if (PF_Password.getText().equals(" Ingrese su contraseña")) {
            PF_Password.setForeground(Color.white);
            PF_Password.setText("");
            PF_Password.setEchoChar('•');
        }
    }//GEN-LAST:event_PF_PasswordFocusGained

    private void PF_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PF_PasswordFocusLost
        if (PF_Password.getText().isEmpty()) {
            PF_Password.setForeground(Color.DARK_GRAY);
            PF_Password.setText(" Ingrese su contraseña");
            PF_Password.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_PF_PasswordFocusLost

    private void PF_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF_PasswordActionPerformed

    }//GEN-LAST:event_PF_PasswordActionPerformed

    private void PF_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PF_PasswordKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            BT_Ingresar.doClick();
        }
    }//GEN-LAST:event_PF_PasswordKeyPressed

    private void BT_VerPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_VerPasswordMousePressed
        PF_Password.setEchoChar((char) 0);
    }//GEN-LAST:event_BT_VerPasswordMousePressed

    private void BT_VerPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_VerPasswordMouseReleased
        PF_Password.setEchoChar('•');
    }//GEN-LAST:event_BT_VerPasswordMouseReleased

    private void L_AccederComoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_AccederComoMouseEntered
        L_AccederComo.setForeground(new Color(0, 216, 224));
    }//GEN-LAST:event_L_AccederComoMouseEntered

    private void L_AccederComoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_AccederComoMouseExited
        L_AccederComo.setForeground(new Color(0, 102, 255));
    }//GEN-LAST:event_L_AccederComoMouseExited

    private void L_AccederComoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_AccederComoMouseClicked
        if (L_AccederComo.getText().equals("Administrador")) {
            L_AccederComo.setText("Profesor");
        } else if (L_AccederComo.getText().equals("Profesor")) {
            L_AccederComo.setText("Alumno");
        } else {
            L_AccederComo.setText("Administrador");
        }
    }//GEN-LAST:event_L_AccederComoMouseClicked

    private void BT_VerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_VerPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_VerPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Ingresar;
    private javax.swing.JButton BT_VerPassword;
    private javax.swing.JLabel L_AccederComo;
    private javax.swing.JLabel L_Contraseña;
    private javax.swing.JLabel L_Titulo;
    private javax.swing.JLabel L_Usuario;
    private javax.swing.JLabel Login_BG;
    private javax.swing.JLabel Login_BG11;
    private javax.swing.JLabel Login_BG12;
    private javax.swing.JLabel Login_BG3;
    private javax.swing.JLabel Login_BG4;
    private javax.swing.JLabel Login_BG5;
    private javax.swing.JLabel Login_BG6;
    private javax.swing.JLabel Login_BG7;
    private javax.swing.JLabel Login_BG8;
    private javax.swing.JLabel Login_BG9;
    private javax.swing.JPasswordField PF_Password;
    private javax.swing.JTextField TF_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
